apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aims-attach-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-retain
  resources:
    requests:
      storage: 20Gi

