apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aims-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-retain
  resources:
    requests:
      storage: 10Gi

